name: Build Example Project

on:
  workflow_dispatch:
  push:
    paths:
      - "Example/**"
      - "Sources/**"
      - "!Sources/Documentation.docc/**"
  pull_request:
    paths:
      - "Example/**"
      - "Sources/**"
      - "!Sources/Documentation.docc/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build example project (Xcode ${{ matrix.xcode }})
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - xcode: 26.0.1
            destination: iPhone 16 Pro
            os: "26.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build\
            -project Example/Example.xcodeproj\
            -scheme Example\
            -sdk iphonesimulator\
            -destination "platform=iOS Simulator,name=${{ matrix.destination }},OS=${{ matrix.os }}"\
          | xcbeautify --renderer github-actions
