name: Build and Test

on:
  workflow_dispatch:
  push:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "!Sources/Documentation.docc/**"
  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "!Sources/Documentation.docc/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  iOS:
    name: Build and test on iOS ${{ matrix.os }} (Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.runner }}
    continue-on-error: true
    strategy:
      matrix:
        include:
          - runner: macos-latest
            xcode: 26.0.1
            destination: iPhone 16 Pro
            os: "26.0"
          - runner: macos-latest
            xcode: 16.4
            destination: iPhone 16 Pro
            os: "18.5"
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: |
          set -o pipefail &&\
          xcodebuild build-for-testing\
            -scheme YouTubePlayerKit\
            -sdk iphonesimulator\
            -destination "platform=iOS Simulator,name=${{ matrix.destination }},OS=${{ matrix.os }}"\
          | xcbeautify --renderer github-actions
      - name: Test
        run: |
          set -o pipefail &&\
          xcodebuild test-without-building\
            -scheme YouTubePlayerKit\
            -sdk iphonesimulator\
            -destination "platform=iOS Simulator,name=${{ matrix.destination }},OS=${{ matrix.os }}"\
          | xcbeautify --renderer github-actions
  macOS:
    name: Build and test on macOS (Xcode ${{ matrix.xcode }})
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - xcode: 26.0.1
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
